FROM golang:latest as builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o desafio ./cmd
RUN update-ca-certificates 

FROM scratch
COPY --from=builder /app/desafio .
ENTRYPOINT ["./desafio"]